<?php
$functions = [
    'report_adeptus_insights_fetch_preview' => [
        'classname'    => 'report_adeptus_insights\\external\\fetch_preview',
        'methodname'   => 'execute',
        'classpath'    => '',
        'description'  => 'Fetch report preview data',
        'type'         => 'read',
        'ajax'         => true,
        'capabilities' => 'moodle/site:viewreports',
    ],
    'report_adeptus_insights_report_crud' => [
        'classname'    => 'report_adeptus_insights\\external\\report_crud',
        'methodname'   => 'execute',
        'classpath'    => '',
        'description'  => 'CRUD operations for reports',
        'type'         => 'write',
        'ajax'         => true,
        'capabilities' => 'moodle/site:viewreports',
    ],
    'report_adeptus_insights_report_parameters' => [
        'classname'    => 'report_adeptus_insights\\external\\report_parameters',
        'methodname'   => 'execute',
        'classpath'    => '',
        'description'  => 'Fetch parameter options for reports',
        'type'         => 'read',
        'ajax'         => true,
        'capabilities' => 'moodle/site:viewreports',
    ],
    'report_adeptus_insights_report_execute' => [
        'classname'    => 'report_adeptus_insights\\external\\report_execute',
        'methodname'   => 'execute',
        'classpath'    => '',
        'description'  => 'Execute a report with parameters',
        'type'         => 'read',
        'ajax'         => true,
        'capabilities' => 'moodle/site:viewreports',
    ],
    'report_adeptus_insights_report_export' => [
        'classname'    => 'report_adeptus_insights\\external\\report_export',
        'methodname'   => 'execute',
        'classpath'    => '',
        'description'  => 'Export report results',
        'type'         => 'read',
        'ajax'         => true,
        'capabilities' => 'moodle/site:viewreports',
    ],
    'report_adeptus_insights_report_history' => [
        'classname'    => 'report_adeptus_insights\\external\\report_history',
        'methodname'   => 'execute',
        'classpath'    => '',
        'description'  => 'User report history and bookmarks',
        'type'         => 'read',
        'ajax'         => true,
        'capabilities' => 'moodle/site:viewreports',
    ],
];
